### ISSUE TITLE
How to use this package with coposer created project. ?

### ISSUE THREAD

**Issue by vrkansagara** [yaegassy/coc-intelephense#12]
I know this can be silly to ask but necessary.

AS VIM user can start editing any system file from the `tabedit` `*.php` file from any location.
So here i am facing issue that autocomplete not fetching library class , method or any variable of it. So how to deal with it

i tried folllowing things.

(1) got to project root and start vim , Result :- only work with imported autoload file only
(2) go to different file where there is no autoload included then it will failed to work

Please guide me how to work in both cases. Thanks in advance. @yaegassy

**Comment by yaegassy** [comment]
I'm sorry, but I don't quite understand your question. I generally don't use tabedit.

> (2) go to different file where there is no autoload included then it will failed to work

What exactly does it mean when you say it fails to work? Can't do completion? Can't make a definition jump?

Are you saying that the problem occurs when you create a new file that is not included in autoload?

**Comment by yaegassy** [comment]
try one of the following.

- Run `:!composer dump-autoload`.
- Run `:CocCommand intelephense.index.workspace`
- Run `:CocRestart`

**Comment by yaegassy** [comment]
As an additional note, I assume you are using `coc-phpls`.

If you want to use `@yaegassy/coc-intelephense`, you need to uninstall `coc-phpls`.

**Comment by vrkansagara** [comment]
@yaegassy  I on my way to confirm this fix. If it not get resolved, I will ask for re-open else otherwise. thanks.

**Comment by yaegassy** [comment]
Please report an issue to coc-phpls

**Comment by vrkansagara** [comment]
@yaegassy  Thanks of the prompt reply on this issue. My question is related to `workspace` which I found from README

![image](https://user-images.githubusercontent.com/12006483/140926733-656e01f9-16dd-42a2-861e-49e0495a5dcc.png)

Let me repeat my use case
- I have many project which having `public/index.php`
- I have few project which having `/index.php`
- Any test file on the file like `/tmp/test.php`

so how can I set `intelephense.environment.documentRoot` dynamically. What is suggested way to work in all the cases? 

> Please report an issue to coc-phpls

Thanks for this, I have already removed `coc-phpls`

**Comment by yaegassy** [comment]
I've never used the `intelephense.environment.documentRoot` setting, so I can't give clear advice. :(

It is probably not possible to set `intelephense.environment.documentRoot` dynamically. I believe the same is true for the related `intelephense.environment.includePaths` setting.

I usually start up one Vim/Neovim in the project root for each project.

If you want to configure settings specific to each project, you can use `:CocLocalConfig` to create a local configuration named `.vim/coc-settings.json` directly under the project root.

If you look upstream issues with the keyword `intelephense.environment.documentRoot`, you may get the information you want.

**See**:

- <https://github.com/bmewburn/vscode-intelephense/issues?q=intelephense.environment.documentRoot>
