### ISSUE TITLE
How to confirm change rename action in different file (not loaded in buffer)?

### ISSUE THREAD

**Issue by Dmitrev** [yaegassy/coc-intelephense#14]
Hi thanks for making the plugin, I enjoy it a lot.
I ran into 1 issue however. Renaming methods of classes that are already used in other files AND are not currently loaded into a buffer seems to not work.

![image](https://user-images.githubusercontent.com/1260209/143661435-76ecf26b-a1be-4ef2-aaf8-32a41f11c044.png)

When I rename this to something else I get this floating text that asks me to confirm, any idea how to do that?

![image](https://user-images.githubusercontent.com/1260209/143661466-adc8fbde-fee1-4c64-b9bd-13242023ef5a.png)

**Comment by yaegassy** [comment]
Hi, when the floating window appears, type `y`. You can check the changed file by running `:copen`.

**DEMO(mp4)**:

https://user-images.githubusercontent.com/188642/143794966-d148be26-a376-49d0-9316-9ea62e0741b1.mp4

**Comment by yaegassy** [comment]
I cannot confirm this issue in my environment, so I will close it.

Also, the Language Server (`intelephense`) itself was updated today. coc-intelephense has already been updated to the latest version.

The Language Server may have been updated, which may have solved this problem. Try it in your environment.

**Comment by Dmitrev** [comment]
Thanks for the vid, I think my env is broken.
