### ISSUE TITLE
Licence.txt or License.txt?

### ISSUE THREAD

**Issue by benyaminl** [yaegassy/coc-intelephense#21]
Hello, does it really need to write licence.txt rather than license.txt? 

Thank you

**Comment by yaegassy** [comment]
Hi, @benyaminl 

Yes, I am. I thought it was "license" at first too, but it seems that "licence" is correct. :)

- See: <https://github.com/bmewburn/vscode-intelephense#licence>

**Comment by benyaminl** [comment]
@yaegassy thanks :D
