### ISSUE TITLE
git init required for laravel projects?

### ISSUE THREAD

**Issue by xebcam** [yaegassy/coc-intelephense#22]
I installed coc-phpls and didn't work (got Undefined types and other errors) then I installed this extension and worked but I noticed that it worked because I initialized my laravel project as a git repo. Then I tried coc-phpls on a project which was also initialized as a git repo and it also worked so this is more of a question rather than an issue. Is it required to have laravel projects initialized as git repos in order for intelephense to "index" or recognize laravel's types, functions, etc?

Also. Nice work! I really like the extension as it seems that other extension have been abandoned. Thanks!

**Comment by yaegassy** [comment]
Hi, @xebcam 

Depending on the project like mono repo or how Vim/Neovim is started, `workspaceFolders` may not be recognized correctly.

It would be a good idea to `cd` command to the "project root" first in your terminal and then start Vim/Neovim there.

To make coc.nvim recognize `workspaceFolders` correctly, you can set `b:coc_root_patterns` in .vimrc/init.vim

**Example**:

```vim
  au FileType php let b:coc_root_patterns = ['.git', '.env', 'composer.json', 'artisan']
```

For more information, check this coc.nvim's wiki.

- <https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders>

**Comment by yaegassy** [comment]
The root pattern can be added on the coc-extension side. In `@yaegassy/coc-intelephense` I added `artisan`. <https://github.com/yaegassy/coc-intelephense/commit/b72ba0b4fb269d43b1f88653669967877e342869>

**Comment by xebcam** [comment]
Wow! I didn't know that. Thank you so much! 👍
