### ISSUE TITLE
@intelephense-ignore-line does not work

### ISSUE THREAD

**Issue by axkirillov** [yaegassy/coc-intelephense#30]
It seems that this feature
https://github.com/yaegassy/coc-intelephense/pull/16
does not work for me
When I trigger CocAction I don't see this option, and adding it manually does not really turn the warning off.
I'm using neovim v0.7.0
and
`✓ @yaegassy/coc-intelephense Current version 0.18.2 is up to date.     `

**Comment by yaegassy** [comment]
This feature is disabled (`false`) by default. Try setting `intelephense.client.diagnosticsIgnoreErrorFeature` to `true` in `coc-settings.json`

```jsonc
{
  // ...snip
  "intelephense.client.diagnosticsIgnoreErrorFeature": true,
  // ...snip
}
```

**Comment by axkirillov** [comment]
@yaegassy thanky you!
