### ISSUE TITLE
Help on snippets / autocompletion

### ISSUE THREAD

**Issue by DaanGeurts** [yaegassy/coc-intelephense#44]
First of all I like to give you a big applause for making all the magic possible. You've made my life so much easier!!!

I've noticed that there are some snippets available within this plugin. But I couldn't find a way to customize these. 
E.G. I want to add some of my own without grabbing another snippet plugin.
Can you push me in the right direction?
Big thanks

**Comment by yaegassy** [comment]
The snippet provided by coc-intelephense itself is very simple and not intended for customization.

It sounds like you don't want to include additional plugins or coc-extension, but again, if you need customization, please add other snippet plugins or coc-extension.  🙇

e.g. `coc-snippets` <https://github.com/neoclide/coc-snippets>.
