### ISSUE TITLE
[coc.nvim] The licence key provided is not valid. Please check you have entered the key correctly.

### ISSUE THREAD

**Issue by Heptite** [yaegassy/coc-intelephense#45]
Unfortunately this error message is ambiguous.  I am sure I entered my key correctly by adding a line to the appropriate licence.txt file, but I still get the error.

**Comment by yaegassy** [comment]
Hi, thant error message is not created by coc-intelephense on its own, but comes from the intelephense's language server itself.

It seems that this error message is output when the licence key is incorrect.

Please double check the licence key in the email you received after purchasing your intelephense licence.

**Comment by yaegassy** [comment]
If you continue to receive error messages even though your licence key is correct, you may want to contact @bmewburn via email using the "Contact" link at <https://intelephense.com/>.

**Comment by Heptite** [comment]
Turns out the key file can't have a newline in it or it will come up as invalid. I once I fixed that the error went away.
