### ISSUE TITLE
How to add a path to index

### ISSUE THREAD

**Issue by xerenahmed** [yaegassy/coc-intelephense#50]
My project using another vendor outside from project path. How to add to the indexing.

**Comment by yaegassy** [comment]
intelephense.environment.includePaths setting may have something to do with it. Give it a try. 

https://github.com/yaegassy/coc-intelephense/blob/master/package.json#L594

**Comment by yaegassy** [comment]
To configure at the project level, place .vim/coc-settings.json

**Comment by xerenahmed** [comment]
Thank you!
