### ISSUE TITLE
intelephense indexing...  Always refreshing and show

### ISSUE THREAD

**Issue by xnwww** [yaegassy/coc-intelephense#57]
After opening the php project,，the prompt of  intelephense  indexing is always displayed and the automatic refresh is not stopped

**Comment by xnwww** [comment]
![image](https://user-images.githubusercontent.com/30192664/225522049-7e44fac2-91bf-49ca-ba78-76da81ec5cb0.png)
As shown in the figure

**Comment by yaegassy** [comment]
If you want to hide the progress display, set `intelephense.progress.enable` to `false`.

**coc-settings.json**:

```jsonc
{
  "intelephense.progress.enable": false
}
```

For large projects, or depending on the condition of your PC, it may take a very long time for the progress display to complete.

To force the progress display to stop, perform the following `:CocCommand intelephense.cancel.indexing`.
